graph_distributed:
	cd ../graph-store-distributed ; make graph_store ; cd ../tools
micro_micro:
	cd ../micro/;make micro;cd ../tools
micro_verb:
	cd ../micro/;make verb;cd ../tools
index_server:
	g++ -std=c++11 index_server.cpp -o index_server.out
minimal_index_server:
	g++ -std=c++11 minimal_index_server.cpp -o minimal_index_server.out
clean:
	rm *.out